sudo: required
services:
  - docker
language: ruby
rvm:
  - 2.2
node_js:
  - 4.1

before_install:
  - bundle install
  - npm install -g bower cli-real-favicon
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - bower install

script:
  - real-favicon generate _assets/img/faviconDescription.json /dev/null .
  - JEKYLL_ENV=production bundle exec jekyll build --future

  - bundle exec yaml-lint _i18n/*.yml .travis.yml _config.yml .scss-lint.yml _data/*.yml docker-compose.yml
  - bundle exec htmlproofer --allow-hash-href --disable-external --check-html  _site
  - bundle exec scss-lint _assets/css

  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH | tr / - ; fi`
  - docker build -t tiltfestival/improfestival-2017:$TAG .
  - docker push tiltfestival/improfestival-2017:$TAG
  - docker rmi tiltfestival/improfestival-2017:$TAG

after_script:
  - docker logout

notifications:
  email:
    on_success: change
    on_failure: change
    recipients:
      - ando@sqroot.eu
